language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: required

services:
    - docker

before_install:
    - docker build -t jdbohrman/thegrowthapp .
    - docker ps -a
    - docker run jdbohrman/thegrowthapp

install:
  - pip install -r requirements.txt
  - pip install .

branches:
  only:
  - dockerized
  - /.*/

script: make test