language: python

sudo: required

services:
    - docker

before_install:
    - docker build -t jdbohrman/thegrowthapp .
    - docker ps -a
    - docker run jdbohrman/thegrowthapp

install:
    - python setup.py install

branches:
  only:
  - dockerized
  - /.*/


script:
    - pytest $PACKAGENAME
