language: python

sudo: required

services:
    - docker
before_install:
    - docker build -t jdbohrman/thegrowthapp .
    - docker run -d -p 127.0.0.1:80:4567 jdbohrman/thegrowthapp /bin/sh -c "cd /root/thegrowthapp; bundle exec foreman start;"
    - docker ps -a
    - docker run jdbohrman/thegrowthapp /bin/sh -c "cd /root/thegrowthapp; bundle exec rake test"

install:
    - python setup.py install

branches:
  only:
  - dockerized
  - /.*/


script:
    - pytest $PACKAGENAME
